title: Andrew Young # your name (or website title) here
logo: "/images/logo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I obtained my M.S. in Statistics from Duke University, one of the top 5 Statistics programs in the world.
  <br><br>
  I have experience as a data scientist, data engineer, analytics engineer, technical product manager and academic researcher. 
  <br><br>
  <a href="https://www.linkedin.com/in/andrewyoung16/">View My LinkedIn Profile</a> 
  <a href="https://github.com/aw236/">View My GitHub</a> 
  
theme: jekyll-theme-minimal
google_analytics: GTM-N33Q4HF # your Google Analytics tracking ID here e.g. GTM-XXXXXXX